plugins {
    id 'net.neoforged.moddev' version '2.0.72'
    id 'maven-publish'
}

version = project.mod_version
group = project.mod_group

base {
    archivesName = project.mod_id + '-' + project.minecraft_version
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        zetter {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // NeoForge and Minecraft dependencies are automatically managed by ModDevGradle.
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version       : neoforge_version,
            neoforge_version_range : neoforge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_version            : mod_version,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching("META-INF/neoforge.mods.toml") {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
