org.gradle.jvmargs=-Xmx3G -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000 -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000

mod_id=zetter
mod_version=0.21.7
mod_group=me.dantaeusb.zetter
mod_name=Zetter
mod_authors=dantaeusb
mod_description=Zetter is a Minecraft mod with a simple goal of adding custom drawing interface to create and use custom pictures in Minecraft.

minecraft_version=1.21.1
neoforge_version=21.1.57
